/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contextmenu: typeof import('./src/components/Contextmenu.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTree: typeof import('element-plus/es')['ElTree']
    Explorer: typeof import('./src/components/Explorer.vue')['default']
    ExplorerContextmenu: typeof import('./src/components/ExplorerContextmenu.vue')['default']
    FileNav: typeof import('./src/components/FileNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
  export interface ComponentCustomProperties {
    vPopover: typeof import('element-plus/es')['ElPopoverDirective']
  }
}
